 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/photo_tags", type: :request do
  
  # PhotoTag. As you add validations to PhotoTag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PhotoTag.create! valid_attributes
      get photo_tags_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      photo_tag = PhotoTag.create! valid_attributes
      get photo_tag_url(photo_tag)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_photo_tag_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      photo_tag = PhotoTag.create! valid_attributes
      get edit_photo_tag_url(photo_tag)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PhotoTag" do
        expect {
          post photo_tags_url, params: { photo_tag: valid_attributes }
        }.to change(PhotoTag, :count).by(1)
      end

      it "redirects to the created photo_tag" do
        post photo_tags_url, params: { photo_tag: valid_attributes }
        expect(response).to redirect_to(photo_tag_url(PhotoTag.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PhotoTag" do
        expect {
          post photo_tags_url, params: { photo_tag: invalid_attributes }
        }.to change(PhotoTag, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post photo_tags_url, params: { photo_tag: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested photo_tag" do
        photo_tag = PhotoTag.create! valid_attributes
        patch photo_tag_url(photo_tag), params: { photo_tag: new_attributes }
        photo_tag.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the photo_tag" do
        photo_tag = PhotoTag.create! valid_attributes
        patch photo_tag_url(photo_tag), params: { photo_tag: new_attributes }
        photo_tag.reload
        expect(response).to redirect_to(photo_tag_url(photo_tag))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        photo_tag = PhotoTag.create! valid_attributes
        patch photo_tag_url(photo_tag), params: { photo_tag: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested photo_tag" do
      photo_tag = PhotoTag.create! valid_attributes
      expect {
        delete photo_tag_url(photo_tag)
      }.to change(PhotoTag, :count).by(-1)
    end

    it "redirects to the photo_tags list" do
      photo_tag = PhotoTag.create! valid_attributes
      delete photo_tag_url(photo_tag)
      expect(response).to redirect_to(photo_tags_url)
    end
  end
end
